### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Aarjav638** [mappls-api/mappls-react-native-sdk#12]
I am Using the mappls react native sdk but for some reasons it is throwing the error.
Maven is not able to find the repository for mappls-android-sdk:8.2.5

help me fix this issue

![Screenshot 2024-10-24 191340](https://github.com/user-attachments/assets/b0f54cce-1273-4a33-8427-d95dac186bfd)

**Comment by harshitjain63** [comment]
I am also getting the exact same error , Is there any Solution of it ?

**Comment by Kishan-Somaiya** [comment]
I'm getting the same error, unable to use the sdk, did you guys find the solution? @Aarjav638 @harshitjain63

**Comment by Saksham66** [comment]
~~~groovy
allprojects {
    repositories {
       maven { url 'https://maven.mappls.com/repository/mappls/'}
    }
}
~~~
Add above code in your android's project level build.gradle
