### ISSUE TITLE
Render custom marker Image ?

### ISSUE THREAD

**Issue by ElangoPrince** [mappls-api/mappls-react-native-sdk#4]
How to use custom marker image inside **MapplsGL.PointAnnotation**? And, how to use **MapplsGL.Images**. ?

<MapplsGL.PointAnnotation id={'id'}>
 </MapplsGL.PointAnnotation>

**Comment by marimuthuhms** [comment]
+1

**Comment by Saksham66** [comment]
Please find the sample:
https://github.com/mappls-api/mappls-react-native-sdk/blob/main/src/scenes/AddCustomMarkerActivity.js
