### ISSUE TITLE
Lat long is  not coming in MapplsGL.RestApi.autoSuggest

### ISSUE THREAD

**Issue by pulkitech-yd** [mappls-api/mappls-react-native-sdk#5]
I am using the MapplsGL.RestApi.autoSuggest and in suggestedLocations latitude and longitude is not coming

**Comment by ShivalThakur** [comment]
HI Team,
I am not getting the lat long details while using autosuggest api.
Can you please help.
Thanks

**Comment by Saksham66** [comment]
You can use mapplsPin to plot the marker or set the location on map
https://github.com/mappls-api/mappls-react-native-sdk/blob/main/src/scenes/AddMapplsPinMarkerActivity.js
