### ISSUE TITLE
Getting error while building code for iOS

### ISSUE THREAD

**Issue by Pratik525** [mappls-api/mappls-react-native-sdk#8]
Tried running the repo code directly without any modifications.
Error : Value of type 'MapplsDirectionViewController' has no member 'shouldShowRouteReportSummary'
<img width="497" alt="Screenshot 2024-03-27 at 10 03 36" src="https://github.com/mappls-api/mappls-react-native-sdk/assets/11808965/5788c8b0-d3f6-46ac-8483-22e2847100c7">

<img width="386" alt="Screenshot 2024-03-27 at 10 04 14" src="https://github.com/mappls-api/mappls-react-native-sdk/assets/11808965/07e5367a-a3b1-4042-9047-4c1d69e030e1">

**Comment by Saksham66** [comment]
Hi @Pratik525,

Please add below line in your podfile:
`pod 'MapplsDirectionUI', '1.0.4'`

Than use `pod deintegrate` and than `pod install`

**Comment by Pratik525** [comment]
@Saksham66 Did the same still the issue persists
Here is how my pod file looks like
<img width="679" alt="Screenshot 2024-03-27 at 15 23 15" src="https://github.com/mappls-api/mappls-react-native-sdk/assets/11808965/7c1b2dcd-3e17-44a2-b79a-2306056e71a3">
